# Generated by Django 5.0.3 on 2024-06-02 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.department'),
        ),
    ]
